version: "3.7"

services:

  app:
    build: ./flask_app
    container_name: flask_app
    restart: always
    ports:
      - "8000:8000"
    # Bind to our local file system with volume 
    # so it auto-updates container when updating locally
    volumes:
      - ./flask_app:/app:ro

  proxy:
    build: nginx
    container_name: nginx-flask
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  app:
