version: "3.7"

services:

  app:
    build: ./flask_app
    container_name: flask_app
    restart: always
    expose:
      - 5000
    ports:
      - "8000:8000"
    volumes:
      - app:/app
  proxy:
    build: nginx
    container_name: nginx-flask
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  app:
